version: "3"
services:
  udagramd-db:
    image: postgres
    networks:
      - udagram
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "udagramdb"
  reverseproxy:
    image: michaelbechay/reverseproxy
    networks:
      - udagram
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - udagramd-db
      - backend-user
      - backend-feed
  backend-user:
    depends_on:
      - udagramd-db
    image: michaelbechay/udagram-api-user
    networks:
      - udagram
    environment:
      POSTGRES_USERNAME: "admin"
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "udagramdb"
      POSTGRES_HOST: localhost 
      AWS_REGION: "eu-west-3"
      AWS_PROFILE: "default"
      AWS_BUCKET: "udagram-esiea-3872"
      JWT_SECRET: "testing"
      URL: "http://localhost:8100"
    command: npm run dev
  backend-feed:
    depends_on:
      - udagramd-db
    image: michaelbechay/udagram-api-feed
    networks:
      - udagram
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: "admin"
      POSTGRES_PASSWORD: 
      POSTGRES_DB: "udagramdb"
      POSTGRES_HOST: localhost
      AWS_REGION: "eu-west-3"
      AWS_PROFILE: "default"
      AWS_BUCKET: "udagram-esiea-3872"
      JWT_SECRET: "testing"
      URL: "http://localhost:8100"
    command: npm run dev
  frontend:
    image: michaelbechay/udagram-frontend:local
    networks:
      - udagram
    ports:
      - "8100:80"
networks:
  udagram:
    name: udagram
